### ISSUE TITLE
Can't establish a connection to the server at ws://127.0.0.1:8000/message

### ISSUE THREAD

**Issue by an-dev** [quantmind/pulsar#117]
Trying django chat example. The code is exactly the same, but still can't find a way to get it right.
![screenshot from 2014-06-18 16 36 11](https://cloud.githubusercontent.com/assets/5052825/3314957/1644880e-f6f6-11e3-907f-7c9624d4aa72.png)

Am I missing something? does it need another server listening to the socket or something?

**Comment by atlantis414** [comment]
Hi lsbardel,
I have a problem. if I run the example by "python manage.py pulse", I couldn't debug the program in IDE as Pycharm? 
or  How to run your example at the same time to debug the program in the IDE
