### ISSUE TITLE
Logging requests with flask

### ISSUE THREAD

**Issue by robgil** [quantmind/pulsar#137]
Hey Folks. I have been trying to figure out how to get flask logs to work when running inside pulsar's wsgi server. I have tried adding the handlers to output to stdout in every place imaginable to get it within context, but I can't get it to work. My goal is to get the werkzeug access logs or just access logs in general to work. If someone has gotten this to work, I would be happy to update the docs with this info.

```
from pulsar.apps import wsgi
from pulsar.apps.wsgi.middleware import middleware_in_executor, wait_for_body_middleware
import logging
import sys

import routes

class Site(wsgi.LazyWsgi):
    def setup(self, environ=None):
        return wsgi.WsgiHandler(
            [wait_for_body_middleware,
             middleware_in_executor(routes.app)])

def run():
    wsgi.WSGIServer(
        callable=Site(),
        workers=4,
        thread_workers=20,
        bind=("0.0.0.0" + ":" + "8080")).start()

if __name__ == '__main__':
    run()
```

This is the server.py. When running routes.py (the standalone flask app), I get the logs.. but not when run from pulsar. 

Any help would be greatly appreciated.

**Comment by lsbardel** [comment]
Hi,
can you add a minimal example in the ``examples`` directory, maybe call it ``flaskapp`` and send me a pull request on the ``dev`` branch. I will take a look. Thanks

**Comment by robgil** [comment]
Thanks @lsbardel.
PR: https://github.com/quantmind/pulsar/pull/138

**Comment by lsbardel** [comment]
When running flask with pulsar, werkzeug server is not used and therefore you need to configure the logger from the command line or the config file. The best way is to do it from the command line.

    python manage.py --log-level routes.info

Check the comment in the commit above.

**Comment by robgil** [comment]
Thank you so much @lsbardel. I will try to get to this in the next couple of days.
