### ISSUE TITLE
Compiled C extension import crashing Python, Windows

### ISSUE THREAD

**Issue by Arttii** [quantmind/pulsar#139]
Hi,

So installed Pulsar on Windows using the latest Anaconda for Python 3.4. The installation was successful, but when I try to import pulsar the interpreter crashes. I narrowed down the issue to 

     from utils import lib

I'm not sure how to get more details as to the reason for it crashing. I tired just building the extensions from source as well does not seem to help. 

Python 3.4.1 |Anaconda 2.1.0 (64-bit). Windows 8.1 64 bit.

**Comment by lsbardel** [comment]
what version of pulsar?

**Comment by Arttii** [comment]
I tried the one from pip and github.  The only conflict I am thinking might occur is that I have python 3 installed as a conda environment, and during the cython compile its using the MinGw bundled with Anaconda for 2.7, but I don't see why that would not work for Python 3.
________________________________

**Comment by lsbardel** [comment]
Can you try installing it via pip and see if it works? Thanks

**Comment by Arttii** [comment]
I did try that. The repl just crashes. I tried using Conda to create a virtual env with Python 3.3 so  the paths do not collide. Now I get :

     ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected      LP_CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO
Readline internal error

This is really confusing me. This looks like a colorama issue, but I even tried uninstalling it. No effect.

**Comment by Arttii** [comment]
The error seems to lie in colorama or pyreadline. Uninstalling pyreadline alleviated the issue. This is discussed in pyreadline/pyreadline#21 and there's a PR to solve it. Uninstalling just seems easier though.

**Comment by lsbardel** [comment]
Is it working for you now?

**Comment by Arttii** [comment]
Yes. So Anaconda users should patch pyreqdline as per the PR or uninstall it.
________________________________
