### ISSUE TITLE
Add an "object proxy" example

### ISSUE THREAD

**Issue by Jiehong** [quantmind/pulsar#143]
Hello,

Perhaps it's me, but the examples of the documentation seem pretty advanced. For example, when we check `Pykka`, the first example is about proxies, but I haven't found how to do something equivalent with pulsar.

Here is what Pykka looks like for this example:

```python
import pykka

class Data(pykka.ThreadingActor):
    pykka_traversable = True
    def __init__(self):
        super(Data, self).__init__()
        self.saved_value = 0
    def inner_method(self):
        return 42

if __name__ == '__main__':
    actor_ref = Data.start()
    actor_proxy = actor_ref.proxy()
    print(actor_proxy.inner_method().get())
    actor_proxy.saved_value = 10
    print(actor_proxy.saved_value)
    
# Output:
# 42
# 10
```

Would it be possible to have an example for this case in the documentation as well?

**Comment by lsbardel** [comment]
Does the greater example do?
https://github.com/quantmind/pulsar/blob/master/examples/snippets/greeter.py

pulsar requires asyncio event loop to run.

**Comment by Jiehong** [comment]
The greeter example shows a class calling a method outside itself, and it also calls the global variable `names` just like that.

I don't get it…

**Comment by lsbardel** [comment]
Please contact the mailing list for this type of questions.
