### ISSUE TITLE
Connection timeout did not set after data processed

### ISSUE THREAD

**Issue by nmg1986** [quantmind/pulsar#151]
```python
 def data_received(self, data):
      '''Delegates handling of data to the :meth:`current_consumer`.
        Once done set a timeout for idle connections when a
        :attr:`~Protocol.timeout` is a positive number (of seconds).
        '''
        self._data_received_count = self._data_received_count + 1
        self.fire_event('data_received', data=data)
        while data:
            consumer = self.current_consumer()
            data = consumer._data_received(data)
            if isinstance(data, Future):
                break
        self.fire_event('data_received', data=data)
```
After `while` loop, does it should be ` self.fire_event('data_processed', data=data)`, otherwise  `connection timeout` will never be set.

**Comment by lsbardel** [comment]
Yes, that is a bug. I'll have a look into it, thanks

**Comment by nmg1986** [comment]
Add also, in

```python
 def _data_received(self, data):
        # Called by Connection, it updates the counters and invoke
        # the high level data_received method which must be implemented
        # by subclasses
        if not hasattr(self, '_request'):
            self.start()
        self._data_received_count = self._data_received_count + 1
        self.fire_event('data_received', data=data)
        result = self.data_received(data)
        self.fire_event('data_processed', data=data)
        return result
```

the `self.fire_event('data_received', data=data)` and `self.fire_event('data_processed', data=data)` seems do noting , when i print out the `event`, i found the handler is `None`, does it necessary to do this here?

**Comment by lsbardel** [comment]
That is expected.
You need to add handlers to these events.
Their use is needed by applications requiring asynchronous behaviour when new data is received at response level.
Check the [proxy server example](https://github.com/quantmind/pulsar/blob/master/examples/proxyserver/manage.py#L159).

**Comment by nmg1986** [comment]
Ok, i known.  
Btw, i am writing a socket chat server, I'm looking forward very much you can give me some `project example` writing with `pulsar`, any suggestions will be appreciated.thank you:)
