### ISSUE TITLE
`Connection`  object can not pickle 

### ISSUE THREAD

**Issue by nmg1986** [quantmind/pulsar#153]
`Connection`  object can not pickle

**Comment by lsbardel** [comment]
No it cannot, and it is not designed to be picklable.
Why do you want to pickle a connection?

**Comment by nmg1986** [comment]
I wanna save it in `redis` for multiprocess access.

If i use a variable to store connection, the variable cannot be shared between processes when i used pulsar with multiprocess model

**Comment by lsbardel** [comment]
I'm not sure that is something you should do.
In any case, the best place to discuss this type of ideas is [pulsar mailing list](https://groups.google.com/forum/?fromgroups#!forum/python-pulsar).
