### ISSUE TITLE
Application can not call other module because pickle, is that in design?

### ISSUE THREAD

**Issue by sbant** [quantmind/pulsar#154]
I have following files:

main.py:
```
# -*- coding: utf-8 -*-
from pulsar.apps import wsgi, Application
import Run
import Proc

def app(environ, start_response):
    print(Run)
    print(Run.proc)

    #Run.proc.do_something()
    #need use the Run.proc object

    start_response('200 OK', [('Content-type', 'text/plain')])
    return [b'OK']


if __name__ == '__main__':
    Run.proc = Proc.Proc()

    wsgi_server = wsgi.WSGIServer(callable=app, bind='127.0.0.1:12456')
    wsgi_server.start()
```

Run.py: (use as program wide object storage)
```
# -*- coding: utf-8 -*-

proc = None
```
Proc.py: (some other module)
```
# -*- coding: utf-8 -*-

class Proc(object):
    def do_something(self, s):
        print(s)
```

I post any thing to the wsgi_server, got these output
< module 'Run' from 'F:/test\\Run.py'>
None

So, the proc in Run.py module is None in the Application function, I found it may be because pulsar pickle the Application function, any way we can deal with this?

**Comment by lsbardel** [comment]
Expected behavior.
Pulsar is designed to work in multiprocessing mode and therefore all application callables must be picklable.
