### ISSUE TITLE
ActorProxyFuture is a class mentioned in docs but doesn't exist in code

### ISSUE THREAD

**Issue by DavidJFelix** [quantmind/pulsar#156]
Is this just a Future of ActorProxy, or is it its own class? The docs seem to explicitly state that it's a class, but searching the source -- it's not there.

**Comment by lsbardel** [comment]
You are right, I have removed all references to ActorProxyFuture. It is now a simple Future.

**Comment by lsbardel** [comment]
http://quantmind.github.io/pulsar/search.html?q=ActorProxyFuture&check_keywords=yes&area=default
