### ISSUE TITLE
test suite does not stop with ctrl-C

### ISSUE THREAD

**Issue by lsbardel** [quantmind/pulsar#158]
The reason being all test classes are loaded in the event loop.

**Comment by lsbardel** [comment]
this has been fixed

**Comment by msornay** [comment]
(I can open a new issue if you prefer)

I'm using Python 3.4 on a Debian Jessie

* Run `python -m runtests --coverage`
* Stop it with ctrl+C
* Run `python -m runtests --coverage` again. It fails with the following output :
```
$ python -m runtests --coverage                                               [15-10-02 14:56]
3.4.3 (default, Sep 17 2015, 15:46:34) 
[GCC 4.9.2]
Coverage file available. Type "coverage html" for a report

Bye (exit code = 2)
```

My solution right now is to use `git clean -fdx` between test executions.

**Comment by lsbardel** [comment]
please, file a different issue.
I cannot replicate it on mac osx.
