### ISSUE TITLE
SERVER_NAME differs from wsgiref

### ISSUE THREAD

**Issue by msornay** [quantmind/pulsar#162]
(when using an ``/etc/hosts`` entry)

Hello,

Consider the following code : 
```python
import wsgiref.simple_server as wsgiref
import pulsar.apps.wsgi as wsgi  
                                                                               
def server_name(environ, start_response):                                                                                                      
    start_response('200 OK', [('Content-Type','text/plain; charset=utf-8')])                                                                   
    return [environ['SERVER_NAME'].encode('utf-8')]
                                               
if __name__ == '__main__':                                                                                                                     
    # wsgi.WSGIServer(callable=server_name).start()                                                                                            
    wsgiref.make_server('0.0.0.0', 8000, server_name).serve_forever()
```

If this runs on a remote server, for which I have an entry "server" in my /etc/hosts and I use : 

 `wget -qO- http://server:8000`

It returns the remote server hostname ( as returned by gethostname() )

When using Pulsar's WSGIServer (with --bind 0.0.0.0:8000) it returns 'server', probably because socket.getfqdn('server') fails in server.py and return its argument (and it takes a lot of time to do so because it triggers a DNS lookup, which is problematic in my setup).

I have not taken the time to dive further in the server.py code yet to make a pull request, but I will unless the fix is obvious to you.

Thanks !

**Comment by lsbardel** [comment]
Hi, not obvious to me, any pull request welcome ;-)

**Comment by lsbardel** [comment]
I've added and endpoint to the ``HttpBin`` router, you can use that for tests if you like

**Comment by msornay** [comment]
Thanks! I'm looking into it.

**Comment by msornay** [comment]
Could you please have a look at https://github.com/msornay/pulsar/commit/633b8622cf48b9d1b676977d8d949afaf01a656e  and give me advices ?

It provides what I think is the correct behavior, i.e. the result of `socket.getfqdn()` on the address returned by `socket.getsockname()`. This is what happens [here](https://github.com/python/cpython/blob/master/Lib/http/server.py#L140).

However : 
* It might not be necessary to do `socket.getfqdn()` on each requests ;
* It might change the way "host errors" are handled in HTTPServerResponse._response ;
* The test I wrote might be incorrect. The bug is only really clear when the remote server running pulsar cannot resolve the HTTP_HOST itself, which is hard to reproduce when the client and the server are on the same machine.

Thanks !

**Comment by lsbardel** [comment]
Looks good to me, can you pull request? I'll code review there and check test passage. Many thanks

**Comment by lsbardel** [comment]
merged with master, thanks!

**Comment by lsbardel** [comment]
@msornay your test fails on mac OS X.

**Comment by msornay** [comment]
I have unfortunately no way of testing that myself. Could you give me the output ? Thanks.

**Comment by lsbardel** [comment]
On my mac when I do:
```python
>>> server = socket.getfqdn('::1')
>>> info = socket.getaddrinfo(server, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".pyenv/versions/3.4.3/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
On a linux box this works fine, therefore it is not a big deal, but it would be nice to have the test working on mac too.
