### ISSUE TITLE
Werkzeug-like MultiValueDict for url_data

### ISSUE THREAD

**Issue by msornay** [quantmind/pulsar#166]
If i use the URL `http://localhost:8060?data=hello&data=world`, the WsgiRequest object as the following behavior :

```
>>> request.url_data
{'data': ['hello', 'world']}

>>> request.url_data['data']
['hello', 'world']
```

But i think it should behave like [Werkzeug](http://werkzeug.pocoo.org/docs/0.10/datastructures/#werkzeug.datastructures.MultiDict) : 

```
>>> request.url_data['data']
'hello'

>>> request.url_data.getlist('data')
['hello', 'world']
```

I believe using `request.url_data['data']` to get a single URL argument is the most common use case (by far) and should not require the array / not array check. 

What do you think ?

**Comment by lsbardel** [comment]
Not sure,
I understand the rationale but i dislike the ``implicit`` behaviour.
That dictionary contains values which are lists and therefore the default behaviour should return the actual value in my opinion.

Do you have a use case where the API you are proposing would be better than the current one?

Alternatively, what about
```python
>>> request.url_data.getfirst('data')
'hello'
```

**Comment by msornay** [comment]
> I understand the rationale but i dislike the implicit behaviour.

I agree with you, but the implicit behavior is already there since access on a single value list returns the item, not the list. An alternative would be to *always* return lists.

> Do you have a use case where the API you are proposing would be better than the current one?

Developers are used to the alternative implemented by Werkzeug (Flask is based on it). Moreover, using the several argument with the same name in the URL is not something that you consider often.

It is not so much about functionnality as it is about security. I'm sure that 9 times out of 10, making a request on an url with the same arguments will make a Pulsar-based app throw a 500 because the developper will not have taken the time to handle it properly (and I think he shoudn't anyway)

**Comment by lsbardel** [comment]
Fair enough, they are all very good arguments.
Please, go ahead with a patch if you like

**Comment by lsbardel** [comment]
This has been superseded by #265
