### ISSUE TITLE
task decorator on standard functions

### ISSUE THREAD

**Issue by msornay** [quantmind/pulsar#167]
Hello,

Maybe I'm misunderstanding the way `task` decorator should be used but consider the following code (Python 3.4) :

```python
import asyncio
from pulsar import task

@task
def func():
    return 42

fut = func()
asyncio.get_event_loop().run_until_complete(fut)
print(fut.result())
```

It fails with : 
```
TypeError: 'int' object is not iterable
```

[This test](https://github.com/quantmind/pulsar/blob/master/pulsar/async/futures.py#L162) feels wrong. I think using `asyncio.coroutine()` to create a coroutine from the `function`argument would be better.

I'll submit a patch as soon as I solve my issues with running the test suite.

**Comment by lsbardel** [comment]
Indeed, to be honest that decorator is somehow there for legacy reason.
I think the test should only be if the ``res`` is a ``Future``.

**Comment by msornay** [comment]
> Indeed, to be honest that decorator is somehow there for legacy reasons.

Interesting. I have been using it on my Routers method to construct the reply in an asynchronous fashion. Am I missing something ?

**Comment by lsbardel** [comment]
That is the correct use for now, at least until python 3.4 is supported.
Once python 3.4 support is dropped (when python 3.6 is released) the task decorator is not that useful anymore. The `async/await` pair will do the job nicely.

The async wsgi specification will include ``native coroutine`` as well as ``futures`` as a possible return value from a wsgi middleware.

**Comment by lsbardel** [comment]
this is now fixed
