### ISSUE TITLE
HTTPException message is not escaped

### ISSUE THREAD

**Issue by msornay** [quantmind/pulsar#172]
When an HTTPException is raised, and [render_error()](https://github.com/quantmind/pulsar/blob/74d1e6e58095679291c14c826ce63f6312a93256/pulsar/apps/wsgi/utils.py#L262) decide to return HTML, the exception message should be escaped to prevent [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting).

[OWASP recommends it](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.231_-_HTML_Escape_Before_Inserting_Untrusted_Data_into_HTML_Element_Content) and [Werkzeug does it.](https://github.com/mitsuhiko/werkzeug/blob/d9e7736de41e7cbf5de70a15e28449b4dd4adab0/werkzeug/exceptions.py#L113)

**Comment by lsbardel** [comment]
Right, but how would the exception message cause XSS?
I'm not an expert, but I'm curious.

**Comment by msornay** [comment]
If the developer re-use user input in an exception message, Pulsar will create HTML from it. If the user input happens to be javascript, it will be executed in the client browser when the error page is displayed.
