### ISSUE TITLE
helloworld example tests is not work

### ISSUE THREAD

**Issue by bright-pan** [quantmind/pulsar#204]
i use the command for helloworld test:
> python -m unittest helloworld.tests -v
test405 (helloworld.tests.TestHelloWorldProcess) ... ok
testMeta (helloworld.tests.TestHelloWorldProcess) ... ok
testResponse (helloworld.tests.TestHelloWorldProcess) ... ok
testTimeIt (helloworld.tests.TestHelloWorldProcess) ... ok
test405 (helloworld.tests.TestHelloWorldThread) ... ok
testMeta (helloworld.tests.TestHelloWorldThread) ... ok
testResponse (helloworld.tests.TestHelloWorldThread) ... ok
testTimeIt (helloworld.tests.TestHelloWorldThread) ... ok

----------------------------------------------------------------------
Ran 8 tests in 0.001s

OK

its looks like work fine, but i modify "hello world!" to "hello asdfsfworld!",
and it output the same, why?

**Comment by dejlek** [comment]
Why would it behave any different? "hello asdfsfworld!" is just yet another string. Have you seen what the test does actually?

**Comment by lsbardel** [comment]
https://github.com/quantmind/pulsar/blob/master/examples/helloworld/tests.py#L46
