### ISSUE TITLE
fixing the setup.py mess

### ISSUE THREAD

**Issue by bristea** [quantmind/pulsar#213]
It seems that the current `setup.py` is a total mess that goes against most python design guidelines. 

A good example is the fact that basic commands line `python3 setup.py --version` do have unpredictable results, as in building the package instead of returning the version, and just the version. `setup.py` was not meant to be used as fancy bash script.

This has to be fixed by using proper setuptools/distools/pip libraries not by trying to replicate some of their functionality inside the `setup.py`.

Here is a simple test case of things that are not supposed to fail:
```
python setup.py --version
python setup.py egg_info
python setup.py bdist_wheel
python setup.py bdist
python setup.py test # should run the tests, instead of the runtests
```
A full list of default commands can be found at https://pythonhosted.org/an_example_pypi_project/setuptools.html -- with the mention that the `bdist_wheel` one is added by `wheel` package itself, which I would recommend using.

Let's hope you agree with this and we will see me or someone making some pull requests that do address this.

**Comment by lsbardel** [comment]
You are right, and I would very much welcome some help on that front.
I have didn't give too much attention to the ``setup.py`` script over the last few years unfortunately. It was written when pulsar was still working on python 2 and 3 with the same codebase.

**Comment by lsbardel** [comment]
this is now fixed in the [dev](https://github.com/quantmind/pulsar/tree/dev) branch.
