### ISSUE TITLE
Switch to pytest and embed its call into setup.py test

### ISSUE THREAD

**Issue by ssbarnea** [quantmind/pulsar#214]
I would advise to use `pytest` to orchestrate test execution and to replace the current `runtests.py` with pytest, which is very powerful and flexible. 

PyTest can easily be called directly by setup.py via the standard `python3 setup.py test` command.

My impression is that it should not be to hard to implement it and I am willing to do it as I already did this for lots of PyPi modules. 

I hope that's also desired by @quantmind

**Comment by lsbardel** [comment]
This is not what I have in mind.
If you want to go down this path you are going to do all the heavy lifting.
Surely we can modify the current test suite to run via the ``python setup.py test`` command!?
