### ISSUE TITLE
package version differs if git is present or not in PATH

### ISSUE THREAD

**Issue by ssbarnea** [quantmind/pulsar#215]
It worries me that the package version returns different results when git is installed as opposed to when it is not, without giving any indications regarding the cause.

I do really like the idea o dynamic versions based on the git changeset history, but still I don't like the fact that the same codebase returns different results based on the environment. 

I discovered this using Parallels, on my Windows VM it did report the alpha version `1.1.4alpha0` because git was missing from path and on OS X it did report a dev version `1.1.4devNNNN`.

Is there something we do something about this? I do feel that many surprises could raise from here.

**Comment by lsbardel** [comment]
Let's not over engineer things.
The ``alpha`` version should not be used in production and therefore no surprises should arise.
To have a consistent alpha version one needs to have git in the path.
