### ISSUE TITLE
How to communicate between two applications in MutiApp?

### ISSUE THREAD

**Issue by bright-pan** [quantmind/pulsar#217]
i create two application, flask wsgi server and Echo server in MutiApp, 
can i send data to Echo server from browser?

How to communicate between two applications in MutiApp?

**Comment by lsbardel** [comment]
You need to give some more details of your setup and goals for someone to be able to help you. In any case this is not the right channel for such enquires.
Github issues are mainly for bug reports and feature requests,
for any other query the [google mail list](https://groups.google.com/forum/?fromgroups#!forum/python-pulsar) is the better place.

**Comment by lsbardel** [comment]
Thanks, quastion asked on the maling list
https://groups.google.com/forum/?fromgroups=#!topic/python-pulsar/_QgkzAlKM0o
