### ISSUE TITLE
JsonProxy is not using utf-8

### ISSUE THREAD

**Issue by wilddom** [quantmind/pulsar#225]
The following line does not work as intended as it does not send requests encoded as utf-8:
`json.dumps(data).encode('utf-8')`

According to the docs I think you should set `ensure_ascii=False`: 
`json.dumps(data, ensure_ascii=False).encode('utf-8')`

> If ensure_ascii is True (the default), all non-ASCII characters in the output are escaped with \uXXXX sequences

**Comment by lsbardel** [comment]
I'm not sure about this to be honest.
The current implementation works fine, clients from other languages can decode JSON strings from pulsar endpoints. Do you have a use case I can take a look?

**Comment by wilddom** [comment]
Well, the endpoint I use unfortunately does not support unicode escape sequences (`\uXXXX`), which actually breaks the JSON specification. But anyway, it would be nice to be able to choose the encoding.

**Comment by lsbardel** [comment]
OK, can you write a patch with a pull request that fix your issue?
I will than take a look.
