### ISSUE TITLE
Content type handling for json-rpc

### ISSUE THREAD

**Issue by wilddom** [quantmind/pulsar#232]
In this [seemingly deprecated document about json rpc v1.2](http://www.jsonrpc.org/historical/json-rpc-over-http.html) there is a recommended content type:

> Content-Type SHOULD be 'application/json-rpc' but MAY be 'application/json' or 'application/jsonrequest'

Unfortunately I'm working with a third party server which is using that content type, but because `application/json-rpc` is not in `pulsar.utils.httpurl.JSON_CONTENT_TYPES` it is not automatically parsed as json.

Should it be added or can you think of a better solution?

**Comment by lsbardel** [comment]
Is this an issue with the ``JsonProxy`` class, the ``HttpClient`` or the pulsar rpc server middleware?
Can you show where your use case fails and why?

**Comment by wilddom** [comment]
In my case I'm using the `JsonProxy` but it's actually the underlying `HttpClient` (the [decode_content](https://github.com/quantmind/pulsar/blob/379914eabcaea2c63def577f83442b38aff85a26/pulsar/apps/http/__init__.py#L662) method) which is parsing json.

**Comment by lsbardel** [comment]
OK, I think the ``JsonProxy`` and ``JsonBatchProxy`` should not call ``decode_content`` but instead the ``json`` method.
The response should always be JSON serialisable.
Can you create a pull request with a fix?
