### ISSUE TITLE
Integrate with other asyncio framework example ?

### ISSUE THREAD

**Issue by greentornado** [quantmind/pulsar#256]
Is it a good idea to mix pulsar with other framework like https://github.com/channelcat/sanic ?

**Comment by lsbardel** [comment]
It depends what you want to do.
If you have a specific question, or would like to discuss possible applications, please ask it in the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/python-pulsar).
Issues are for bug reports and feature requests.
