### ISSUE TITLE
Error while installing pulsar on Windows

### ISSUE THREAD

**Issue by wojpie** [quantmind/pulsar#260]
Hi,

I'm trying to install pulsar using pip, but during the installation the following error appears:

`AttributeError: module 'signal' has no attribute 'SIGQUIT'`

I'm using Python 3.5. Is there any way to solve this issue?

**Comment by lsbardel** [comment]
This is fixed in 1.6.2
https://github.com/quantmind/pulsar/releases/tag/1.6.2

however, pulsar in windows does not currently support multi process. Therefore when running servers always pass ``-w 0``
