### ISSUE TITLE
Is clustering supported?

### ISSUE THREAD

**Issue by erikash** [quantmind/pulsar#266]
Hi,
Is there a way to have multiple instances of a pulsar application and have actors communicate between machines?

Kudos for the great project!
Erik

**Comment by lsbardel** [comment]
In theory it is possible, do you have a use case for such architecture?
Thanks for the kudos

**Comment by erikash** [comment]
Thanks for the quick response!

The simplest use case is batch processing (multiple machines needed for performance), in which a Monitor which needs to coordinate actors across machines.

Another use case is consistent hashing or another sharding scheme in which an actor is assigned a chunk of data to process commands, this requires the monitor to intelligently route commands to the matching actors.

Does this make sense?

Thanks,
Erik.

**Comment by lsbardel** [comment]
This is a very interesting topic, Worth discussing on the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/python-pulsar) if you are interested.
At the moment cross-node interaction is not supported out of the box but I don't see why it couldn't in the future.

But, is it a useful feature? Will people use it? I'm not so sure.

There are many way of achieving cross-node interaction, [pulsar-queue](https://github.com/quantmind/pulsar-queue) is a project that tackle the problem using a distributed task queue. Not the same thing but another cluster/type application.

I'm closing this ticket for now as it does not fit into our workflow.
Please bring the question to the mailing list if you care about it, I'll be happy to bounce ideas.
