### ISSUE TITLE
CI release process

### ISSUE THREAD

**Issue by lsbardel** [quantmind/pulsar#271]
Currently we release pulsar manually, running the release script.
We should run the script in the CI environment and build wheels for all platforms.

**Comment by sideffect0** [comment]
is release script private(not in public code) ?

**Comment by wellls** [comment]
@sideffect0 I think release script is public, it's in this [folder](https://github.com/quantmind/pulsar/tree/master/.ci)

**Comment by sideffect0** [comment]
what is blocking it from running the script in CI ?

**Comment by lsbardel** [comment]
Time unfortunately 😢 
I don't have time for pulsar at this precise moment unfortunately and the release script needs testing and love.
If you have suggestions/fixes I'll be very happy to guide you in the right direction and review pull requests in needed.

**Comment by sideffect0** [comment]
Am happy to contribute/help :)

**Comment by sideffect0** [comment]
@lsbardel  we can use https://www.appveyor.com/ for windows builds

**Comment by lsbardel** [comment]
yes, that is already in the pipeline of 2.0, https://github.com/quantmind/pulsar/blob/dev/appveyor.yml

**Comment by lsbardel** [comment]
This is done
https://github.com/quantmind/pulsar/releases/tag/2.0.1
