### ISSUE TITLE
Question regarding Pulsar Actor State

### ISSUE THREAD

**Issue by dkhan11** [quantmind/pulsar#272]
* **pulsar version**:
Latest.
* **python version**:
3.5.*
* **platform**:
Linux

## Description

Hi,
The Actor model states that actors do not share state, but they do hold their internal state.
How does Pulsar implement this? I haven't seen clear way to to add data to the internal state other than 'info_state'. 
Also, since Pulsar is distributed, how should one handle state management in a distributed environment?

Pulsar should have a way to manage Actor state and manage some sort of locking if needed.

Thanks in advance,
DD.

**Comment by lsbardel** [comment]
This seems like a good question, but not an issue with pulsar per se.
Can you ask the question in the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/python-pulsar)?
Perhaps other users can share their experience there.
Maybe [this example](https://github.com/quantmind/pulsar/blob/master/examples/snippets/remote.py) can give you some ideas?

Closing the issue and hopefully see you question in the mailing list
