### ISSUE TITLE
pulsar.apps.wsgi.middleware_in_executor is not pickleable

### ISSUE THREAD

**Issue by Triquetra** [quantmind/pulsar#273]
* **pulsar version**: 1.6.4
* **python version**: 3.5
* **platform**: Alpine Linux

## Description

Running a wsgi server with [the documentation](https://quantmind.github.io/pulsar/tutorials/wsgi.html) recommended pattern fails.

## Expected behaviour

The server runs.

## Actual behaviour

```
File "/home/weppy/myapp.py", line 19, in <module>
    server.start()
  File "/usr/lib/python3.5/site-packages/pulsar/apps/__init__.py", line 350, in start
    on_start = self()
  File "/usr/lib/python3.5/site-packages/pulsar/apps/__init__.py", line 459, in __call__
    actor = pulsar.arbiter(cfg=self.cfg.clone())
  File "/usr/lib/python3.5/site-packages/pulsar/utils/config.py", line 383, in clone
    return pickle.loads(pickle.dumps(self))
AttributeError: Can't pickle local object 'middleware_in_executor.<locals>._'
```

## Steps to reproduce

Given:
```
from weppy import App
app = App(__name__)


@app.route("/")
def hello():
    return "Hello WEPPY on Pulsar!"


def pulsar_with_handler():
    from pulsar.apps import wsgi
    handler = wsgi.WsgiHandler([wsgi.wait_for_body_middleware,
                                wsgi.middleware_in_executor(app)])
    server = wsgi.WSGIServer(callable=handler)
    server.start()


def pulsar_without_handler():
    from pulsar.apps import wsgi
    server = wsgi.WSGIServer(callable=app)
    server.start()
```

pulsar_without_handler() works.
pulsar_with_handler() fails with the above specified error.  The same error is produced on Windows 10 running Python 3.6.

**Comment by Triquetra** [comment]
This seems to be an issue with weppy App objects not being pickleable (see weppy issue linked above).  Is there a way to run Pulsar in non-blocking mode or with greenlets that does not pickle the callable?

**Comment by lsbardel** [comment]
You can use the the [LazyWsgi](https://github.com/quantmind/pulsar/blob/c8153f9bfdd44a6392815c02e6a4d11ed42e27fe/pulsar/apps/wsgi/handlers.py#L84) in these situations.
```python
from pulsar.apps import wsgi


class Site(wsgi.LazyWsgi):

    def setup(self, environ=None):
        from mymodule import app
        return wsgi.WsgiHandler((wsgi.wait_for_body_middleware,
                                 wsgi.middleware_in_executor(app)))


def server(**kwargs):
    return wsgi.WSGIServer(Site(), **kwargs)


if __name__ == '__main__':  # pragma    nocover
    server().start()
```

From pulsar 2.0 this will be done automatically by pulsar.

**Comment by Triquetra** [comment]
Thanks.  That worked.
