### ISSUE TITLE
How to spawn a Actor with `spawn(start=<CoroutineFunction>)`

### ISSUE THREAD

**Issue by RyanKung** [quantmind/pulsar#300]
On pulsar 1.x, it works with:

```python

async def some_fn(*args, *kwargs):
       foo

monitor.spawn(start=some_fn)

```

And on 2.0:

It will warning coroutine was never waited.

**Comment by lsbardel** [comment]
yes, events cannot be coroutines, the event dispatching mechanism was very slow and it has been changed so that no waiting for asynchronous events is supported.
In your case, you need to warp the coroutine in a task with the ``ensure_future`` function.
```python
async def some_fn(*args, *kwargs):
       foo

monitor.spawn(start=lambda: ensure_future(some_fn()))
```
Do you have a use case for this?

**Comment by RyanKung** [comment]
Thanks, `ensure_future` is exactly what I need, I'm just switching to pulsar 2.0.  🥂

**Comment by lsbardel** [comment]
closing
