### ISSUE TITLE
Add pulsar to the web framework benchmarks

### ISSUE THREAD

**Issue by derekchiang** [quantmind/pulsar#93]
It'd be nice to have Pulsar on the [web framework benchmarks](http://www.techempower.com/benchmarks/).

**Comment by lsbardel** [comment]
If anyone is interested in adding pulsar to these benchmarks, you could use [pulsar-odm](https://github.com/quantmind/pulsar-odm) as the asynchronous driver of sqlalchemy ORM.

**Comment by lsbardel** [comment]
we'll have our own benchmark suite #268
